language: generic # don't install any environment
script:
  - make docs
env:
  global:
  - ENCRYPTION_LABEL: "a083722bc806"
  - COMMIT_AUTHOR_EMAIL: "travis@valvex.io"

language: erlang
otp_release:
  - 18.0
  - 18.1
  - 18.2
  - 18.2.1
script:
  - make check
  - make test
